<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="8.0.2" />
    <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" Version="8.0.2" />
    <PackageReference Include="MassTransit" Version="8.3.4" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Planning.Application\Planning.Application.csproj" />
    <ProjectReference Include="..\Planning.Infrastructure\Planning.Infrastructure.csproj" />
    <ProjectReference Include="..\Planning.Domain\Planning.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\building-blocks\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\building-blocks\Settings\Calendarun.Settings.Client\Calendarun.Settings.Client.csproj" />
  </ItemGroup>

</Project>
