// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Settings.Infrastructure;

#nullable disable

namespace Settings.Infrastructure.Migrations
{
    [DbContext(typeof(SettingsDbContext))]
    partial class SettingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Settings.Domain.SettingAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NewValueJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldValueJson")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("SettingAudits");
                });

            modelBuilder.Entity("Settings.Domain.SettingDefinition", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonSchema")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Key");

                    b.ToTable("SettingDefinitions");

                    b.HasData(
                        new
                        {
                            Key = "notifications.smtp.host",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "SMTP Host",
                            IsRequired = true,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "String"
                        },
                        new
                        {
                            Key = "notifications.smtp.port",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "SMTP Port",
                            IsRequired = true,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "Integer"
                        },
                        new
                        {
                            Key = "notifications.smtp.from",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Default From Email",
                            IsRequired = true,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "String"
                        },
                        new
                        {
                            Key = "notifications.email.subject_template",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Email Subject Template",
                            IsRequired = false,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "String"
                        },
                        new
                        {
                            Key = "notifications.email.body_template",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Email Body Template",
                            IsRequired = false,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "String"
                        },
                        new
                        {
                            Key = "notifications.reminder.offsets_minutes",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Reminder offsets in minutes",
                            IsRequired = false,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "StringArray"
                        },
                        new
                        {
                            Key = "notifications.dispatcher.max_attempts",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Max retry attempts for notifications",
                            IsRequired = false,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "Integer"
                        },
                        new
                        {
                            Key = "notifications.dispatcher.batch_size",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Batch size for notification dispatcher",
                            IsRequired = false,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "Integer"
                        },
                        new
                        {
                            Key = "notifications.dispatcher.retry_backoff_base_seconds",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Base seconds for exponential retry backoff",
                            IsRequired = false,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "Integer"
                        },
                        new
                        {
                            Key = "planning.default_timezone",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Default Timezone",
                            IsRequired = true,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "String"
                        },
                        new
                        {
                            Key = "planning.max_plans_per_user",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Max plans per user",
                            IsRequired = false,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "Integer"
                        },
                        new
                        {
                            Key = "platform.invite.expiration_days",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Invite expiration in days",
                            IsRequired = false,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "Integer"
                        },
                        new
                        {
                            Key = "platform.membership.cache_ttl_minutes",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Membership validation cache TTL in minutes",
                            IsRequired = false,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "Integer"
                        },
                        new
                        {
                            Key = "gateway.http_client.timeout_seconds",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Gateway HTTP client timeout in seconds",
                            IsRequired = false,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "Integer"
                        },
                        new
                        {
                            Key = "audit.default_page_size",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Default page size for audit log queries",
                            IsRequired = false,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "Integer"
                        },
                        new
                        {
                            Key = "event.distances",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Available event distances (km, label, displayOrder)",
                            IsRequired = false,
                            IsSensitive = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueType = "Json"
                        });
                });

            modelBuilder.Entity("Settings.Domain.SettingValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Key", "TenantId", "Environment")
                        .IsUnique();

                    b.ToTable("SettingValues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000001"),
                            Environment = "dev",
                            Key = "notifications.smtp.host",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "\"localhost\"",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000002"),
                            Environment = "dev",
                            Key = "notifications.smtp.port",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "1025",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000003"),
                            Environment = "dev",
                            Key = "notifications.smtp.from",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "\"noreply@calendarun.local\"",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000004"),
                            Environment = "dev",
                            Key = "notifications.email.subject_template",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "\"You planned event: {EventId}\"",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000005"),
                            Environment = "dev",
                            Key = "notifications.email.body_template",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "\"Hello!\\n\\nYou have planned event {EventId}.\\nPlan ID: {PlanItemId}\\n\\nBest regards,\\nCalendaRun Team\"",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000006"),
                            Environment = "dev",
                            Key = "notifications.reminder.offsets_minutes",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "[1440, 60, 15]",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000009"),
                            Environment = "dev",
                            Key = "notifications.dispatcher.max_attempts",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "3",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000010"),
                            Environment = "dev",
                            Key = "notifications.dispatcher.batch_size",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "50",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000011"),
                            Environment = "dev",
                            Key = "notifications.dispatcher.retry_backoff_base_seconds",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "10",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000007"),
                            Environment = "dev",
                            Key = "planning.default_timezone",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "\"Europe/Istanbul\"",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000008"),
                            Environment = "dev",
                            Key = "planning.max_plans_per_user",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "100",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000012"),
                            Environment = "dev",
                            Key = "platform.invite.expiration_days",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "7",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000013"),
                            Environment = "dev",
                            Key = "platform.membership.cache_ttl_minutes",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "5",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000014"),
                            Environment = "dev",
                            Key = "gateway.http_client.timeout_seconds",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "5",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000015"),
                            Environment = "dev",
                            Key = "audit.default_page_size",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "50",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000016"),
                            Environment = "dev",
                            Key = "event.distances",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 12, 25, 10, 42, 51, 839, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "[{\"km\":5,\"label\":\"5K\",\"displayOrder\":1},{\"km\":10,\"label\":\"10K\",\"displayOrder\":2},{\"km\":21,\"label\":\"21K\",\"displayOrder\":3},{\"km\":42,\"label\":\"42K\",\"displayOrder\":4},{\"km\":100,\"label\":\"ultra\",\"displayOrder\":5}]",
                            Version = 1L
                        });
                });

            modelBuilder.Entity("Settings.Domain.SettingValue", b =>
                {
                    b.HasOne("Settings.Domain.SettingDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });
#pragma warning restore 612, 618
        }
    }
}
